name: "Plan and Deploy GitHub infrastructure"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-infrastructure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install CDKTF
        run: npm install -g cdktf-cli@latest

      - name: Install dependencies
        run: npm ci

      - name: Run cdktf diff
        run: cdktf diff

