name: "Plan and Deploy GitHub infrastructure"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
  AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
  AZURE_TFSTATE_KEY: $ {{ secrets.AZURE_TFSTATE_KEY }}

jobs:
  diff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-infrastructure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install CDKTF
        run: npm install -g cdktf-cli@latest

      - name: Install dependencies
        run: npm ci

      - name: Run cdktf diff
        run: cdktf diff

  # another_job:
  #   runs-on: ubuntu-latest
  #   env:
  #     AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
  #     AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  #     AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
  #     AZURE_TFSTATE_KEY: ${{ secrets.AZURE_TFSTATE_KEY }}
  #   steps:
  #     ...existing code...

